"""add tickets and approval requests

Revision ID: 0d3f6b0eb934
Revises: 0178cc93b660
Create Date: 2026-09-02 17:04:55.084620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '0d3f6b0eb934'
down_revision: Union[str, Sequence[str], None] = '0178cc93b660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_requests',
    sa.Column('id', app.db.models.UUIDType(length=36), nullable=False),
    sa.Column('tenant_id', app.db.models.UUIDType(length=36), nullable=False),
    sa.Column('requested_by_user_id', app.db.models.UUIDType(length=36), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by_user_id', app.db.models.UUIDType(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', app.db.models.UUIDType(length=36), nullable=False),
    sa.Column('tenant_id', app.db.models.UUIDType(length=36), nullable=False),
    sa.Column('created_by_user_id', app.db.models.UUIDType(length=36), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('approval_requests')
    # ### end Alembic commands ###
